version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  
  mongo:
    container_name: mongodb
    image: 'mongo:3.6.0'
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db

  server:
    container_name: bright-BE
    build: .
    command: npm start
    ports:
      - 5000:5000
      # - 9229:9229 # debugging
    # volumes:
      # - .:/user/src/bright/backend # map current wrkdir with docker wrkdir
      # - /usr/src/bright/backend/node_modules # do not map with local wrkdir
    depends_on:
      - redis
      - mongo

volumes:
  db: