export const LANGUAGE_DEFAULT = 'vi';

export const ERROR_CODE = {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    RATELIMITED: 'RATELIMITED',
    SERVER_MAINTENANCE: 'SERVER_MAINTENANCE',
};

export const AUTH_ACTION = ['login', 'signup']